const ROUTES = {
  MAIN: '/',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  NOTICE: '/notice',
  PARTY: '/party/:partyId',
  SCHEDULE: 'schedule',
  SCHEDULE_COMMENT: '/party/:partyId/schedule-comment',
  PLAN: 'plan',
  ALBUM: '/album',
  LIKE: '/like',
  LIKE_DETAIL: '/like-route/:partyId',
  PARTY_CREATE: '/party/new',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  PLACE_NEW: '/place/new',
  PLACE_EDIT: '/place/edit',
  PLACE_DETAIL: '/place/:placeId',
  PARTY_LIST: '/party-list',
  BEST_ROUTE_LIST: '/best-route-list',
  BEST_ROUTE_DETAIL: '/best-route/:partyId',
  LANDING: '/landing',
  NOTFOUND: '/notfound',
  INVITATION: '/invitation/:roomId',
} as const;

export default ROUTES;
